### ISSUE TITLE
Further Docker image optimization

### ISSUE THREAD

**Issue by syuan100** [syuan100/rosetta-helium#2]
I've been able to get the docker image down to about 600MB for now using the erlang alpine image. Docker is not my strong suit, so would appreciate if someone could take look and further optimize how it's current constructed.

**Comment by rsnodgrass** [comment]
The biggest issue with the final image size is that gcc is being added in the runner stage.  Is gcc actually needed in the final build? (typically no)  I can submit a PR with the proposed change if you agree it shouldn't be included.

**Comment by rsnodgrass** [comment]
I believe gcc and go are not necessary in the final package, since both are for compiling the binaries and aren't needed at runtime.

**Comment by rsnodgrass** [comment]
I've cut it down to about 245MB, will submit PR shortly.

**Comment by syuan100** [comment]
Will take a look now, thanks for reviewing!

**Comment by rsnodgrass** [comment]
If gcc can be pulled out of the runtime Docker image build, this would save another 150MB or so.

**Comment by syuan100** [comment]
I haven't tried, I was was mostly making sure that everything would compile, but yeah since gcc is a build tool I might try pulling it out to see how it works.
